--create sequence
CREATE SEQUENCE AUTO_INCRE_SEQ_ABSENT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AUTO_INCRE_SEQ_DEPARTMENT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AUTO_INCRE_SEQ_EMPLOYEE
START WITH 1
INCREMENT BY 1;


CREATE SEQUENCE AUTO_INCRE_SEQ_ISSUE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AUTO_INCRE_SEQ_ISSUE_HIS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AUTO_INCRE_SEQ_POSITION
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AUTO_INCRE_SEQ_PROJECT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AUTO_INCRE_SEQ_ROLE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AUTO_INCRE_SEQ_STATUS
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AUTO_INCRE_SEQ_STATUS_TYPE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AUTO_INCRE_SEQ_TEAM
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE AUTO_INCRE_SEQ_EMP_ISSUE
START WITH 1
INCREMENT BY 1;
